### PR TITLE
feat(snap): implement rich config hook

### PR DESCRIPTION
**Pull request by tonyespy**
Signed-off-by: Tony Espy <espy@canonical.com>

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/device-rest-go/blob/master/.github/CONTRIBUTING.md

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## New Imports

- [ ] Yes
- [ ] No

### CODE REVIEW

**Review by siggiskulason — COMMENTED** [review]
This builds, but I found two issues

1) the config hook does not run and the .env file is not generated. running with debug=true shows that the configuration code doesn't execute.
The solution is just to 
- git rm snap/hooks/configure
- git rm snap/hooks/install
it seems that if those files are there, then they are used rather than the go hooks.

2) If I remove those two files, then the rich config hook runs but there is something wrong with the validation.  I can basically set any setting without an error, i.e:

```
sudo snap set edgex-device-rest env.random.setting=124
```
and the go hook accepts the setting with no error, adds it to the JSON map and it's then inserted into the .env file, but as an empty string, which breaks the config hook, i.e 

```
$ more /var/snap/edgex-device-rest/current/config/device-rest-go/res/device-rest-go.env 
export =124
```

I believe the clue may be that device-rest passes nil as the extraConf argument to HandleEdgeXConfig. In our update yesterday we missed one thing there. We have

```
env, ok := ConfToEnv[k]
		if !ok && extraConf!= nil {
			env, ok = extraConf[k]
			if !ok {
				return errors.New("invalid EdgeX config option - " + k)
			}
		}
```

So that doesn't handle the case if !ok && extraConf==nil, which is what we have here, with unexpected results. We should therefore probably change this to the following, re-release the snap hooks, update the go.mod reference in device-rest and that should resolve it:

```
if !ok {
    if extraConf!= nil {
	    env, ok = extraConf[k]
		}        
    if !ok {
	    return errors.New("invalid EdgeX config option - " + k)
	}
}
```

**Comment by tonyespy** [comment]
Thanks for the additional testing and reported bugs. All issues have been addressed and I've force pushed this branch to pull in a new version of edgex-snap-hooks with the fix.

The following have now been resolved:

 - bash configure & install hooks removed
 - bug where extraConf == nil has been fixed
   - a new version of edgex-snap-hooks (v0.9.0) fixes the issue
   - unit test added to test the new code
   - trello card created for improving test coverage of this module
   
*Note* -- in addition to the device services, we probably also want to update the edgexfoundry and app-service-configurable snaps.

**Comment by tonyespy** [comment]
Also note, I created the following PRs for edgexfoundry and device-modbus:

- https://github.com/canonical/edgex-device-modbus-go/pull/4
- https://github.com/canonical/edgex-go/pull/32

We'll also need PRs for camera, and mqtt, and app-service-config. I'll try to get to them a bit later. Any help with reviews would be most appreciated. I should be able to handle tagging and snap builds.

**Review by siggiskulason — APPROVED** [review]
LGTM. confirmed it processes correct env settings and rejects invalid ones.

**Pull request merged**
